
import { Country } from './types';

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", code: "af", capital: "Kabul", currency: "Afghani", region: "Asia", population: "40.1M" },
  { name: "Albania", code: "al", capital: "Tirana", currency: "Lek", region: "Europe", population: "2.8M" },
  { name: "Algeria", code: "dz", capital: "Algiers", currency: "Dinar", region: "Africa", population: "44.6M" },
  { name: "Argentina", code: "ar", capital: "Buenos Aires", currency: "Peso", region: "Americas", population: "45.8M" },
  { name: "Australia", code: "au", capital: "Canberra", currency: "Dollar", region: "Oceania", population: "25.7M" },
  { name: "Austria", code: "at", capital: "Vienna", currency: "Euro", region: "Europe", population: "8.9M" },
  { name: "Belgium", code: "be", capital: "Brussels", currency: "Euro", region: "Europe", population: "11.6M" },
  { name: "Brazil", code: "br", capital: "Brasília", currency: "Real", region: "Americas", population: "214.3M" },
  { name: "Canada", code: "ca", capital: "Ottawa", currency: "Dollar", region: "Americas", population: "38.2M" },
  { name: "Chile", code: "cl", capital: "Santiago", currency: "Peso", region: "Americas", population: "19.2M" },
  { name: "China", code: "cn", capital: "Beijing", currency: "Yuan", region: "Asia", population: "1.4B" },
  { name: "Colombia", code: "co", capital: "Bogotá", currency: "Peso", region: "Americas", population: "51.3M" },
  { name: "Croatia", code: "hr", capital: "Zagreb", currency: "Euro", region: "Europe", population: "4.0M" },
  { name: "Czech Republic", code: "cz", capital: "Prague", currency: "Koruna", region: "Europe", population: "10.7M" },
  { name: "Denmark", code: "dk", capital: "Copenhagen", currency: "Krone", region: "Europe", population: "5.8M" },
  { name: "Egypt", code: "eg", capital: "Cairo", currency: "Pound", region: "Africa", population: "109.3M" },
  { name: "Finland", code: "fi", capital: "Helsinki", currency: "Euro", region: "Europe", population: "5.5M" },
  { name: "France", code: "fr", capital: "Paris", currency: "Euro", region: "Europe", population: "67.5M" },
  { name: "Germany", code: "de", capital: "Berlin", currency: "Euro", region: "Europe", population: "83.2M" },
  { name: "Greece", code: "gr", capital: "Athens", currency: "Euro", region: "Europe", population: "10.6M" },
  { name: "Hungary", code: "hu", capital: "Budapest", currency: "Forint", region: "Europe", population: "9.7M" },
  { name: "Iceland", code: "is", capital: "Reykjavik", currency: "Krona", region: "Europe", population: "372K" },
  { name: "India", code: "in", capital: "New Delhi", currency: "Rupee", region: "Asia", population: "1.4B" },
  { name: "Indonesia", code: "id", capital: "Jakarta", currency: "Rupiah", region: "Asia", population: "273.8M" },
  { name: "Ireland", code: "ie", capital: "Dublin", currency: "Euro", region: "Europe", population: "5.0M" },
  { name: "Israel", code: "il", capital: "Jerusalem", currency: "Shekel", region: "Asia", population: "9.4M" },
  { name: "Italy", code: "it", capital: "Rome", currency: "Euro", region: "Europe", population: "59.1M" },
  { name: "Japan", code: "jp", capital: "Tokyo", currency: "Yen", region: "Asia", population: "125.7M" },
  { name: "Kenya", code: "ke", capital: "Nairobi", currency: "Shilling", region: "Africa", population: "55.0M" },
  { name: "Malaysia", code: "my", capital: "Kuala Lumpur", currency: "Ringgit", region: "Asia", population: "32.7M" },
  { name: "Mexico", code: "mx", capital: "Mexico City", currency: "Peso", region: "Americas", population: "126.7M" },
  { name: "Netherlands", code: "nl", capital: "Amsterdam", currency: "Euro", region: "Europe", population: "17.5M" },
  { name: "New Zealand", code: "nz", capital: "Wellington", currency: "Dollar", region: "Oceania", population: "5.1M" },
  { name: "Nigeria", code: "ng", capital: "Abuja", currency: "Naira", region: "Africa", population: "213.4M" },
  { name: "Norway", code: "no", capital: "Oslo", currency: "Krone", region: "Europe", population: "5.4M" },
  { name: "Pakistan", code: "pk", capital: "Islamabad", currency: "Rupee", region: "Asia", population: "231.4M" },
  { name: "Peru", code: "pe", capital: "Lima", currency: "Sol", region: "Americas", population: "33.4M" },
  { name: "Philippines", code: "ph", capital: "Manila", currency: "Peso", region: "Asia", population: "111.0M" },
  { name: "Poland", code: "pl", capital: "Warsaw", currency: "Zloty", region: "Europe", population: "37.8M" },
  { name: "Portugal", code: "pt", capital: "Lisbon", currency: "Euro", region: "Europe", population: "10.3M" },
  { name: "Saudi Arabia", code: "sa", capital: "Riyadh", currency: "Riyal", region: "Asia", population: "35.3M" },
  { name: "Singapore", code: "sg", capital: "Singapore", currency: "Dollar", region: "Asia", population: "5.5M" },
  { name: "South Africa", code: "za", capital: "Pretoria", currency: "Rand", region: "Africa", population: "59.4M" },
  { name: "South Korea", code: "kr", capital: "Seoul", currency: "Won", region: "Asia", population: "51.7M" },
  { name: "Spain", code: "es", capital: "Madrid", currency: "Euro", region: "Europe", population: "47.4M" },
  { name: "Sweden", code: "se", capital: "Stockholm", currency: "Krona", region: "Europe", population: "10.4M" },
  { name: "Switzerland", code: "ch", capital: "Bern", currency: "Franc", region: "Europe", population: "8.7M" },
  { name: "Thailand", code: "th", capital: "Bangkok", currency: "Baht", region: "Asia", population: "71.6M" },
  { name: "Turkey", code: "tr", capital: "Ankara", currency: "Lira", region: "Asia", population: "84.8M" },
  { name: "Ukraine", code: "ua", capital: "Kyiv", currency: "Hryvnia", region: "Europe", population: "43.8M" },
  { name: "United Arab Emirates", code: "ae", capital: "Abu Dhabi", currency: "Dirham", region: "Asia", population: "10.0M" },
  { name: "United Kingdom", code: "gb", capital: "London", currency: "Pound", region: "Europe", population: "67.3M" },
  { name: "United States", code: "us", capital: "Washington, D.C.", currency: "Dollar", region: "Americas", population: "331.9M" },
  { name: "Vietnam", code: "vn", capital: "Hanoi", currency: "Dong", region: "Asia", population: "97.5M" }
];
